### ISSUE TITLE
Create GitHub release when tagged and binary packages of Poppy

### ISSUE THREAD

**Issue by adulau** [hashlookup/poppy#5]
- Adding GitHub releases when tagged
- Adding binary packages for easy installation of Poppy

**Comment by qjerome** [comment]
The magic with Rust cargo is that users can install binaries provided by some crates, and even the version they want.
For instance one can install latest `poppy` binary with `cargo install poppy-filters` or a specific version with `cargo install --version A.B.C poppy-filters`. This will download and compile the good `poppy` binary and put it in `$HOME/.cargo/bin`.
Moreover cargo install can also be used to install the binary at a custom location.
So to say that when publishing crates on crates.io, I think managing GH releases cycles might sound a bit like double work.
